POST http://127.0.0.1:8000/shop_api/shops/1/
Content-Type: application/json

{
    "id": 1,
    "shop_owner": "PINTU",
    "shop_name": "Exam Wishes",
    "description":"EWP GTD",
    "open_date": "4 March 2021",
    "display_picture": "https://pintusingapura.org/static/image/paket01-2021.jpg",
    "closed_date": "10 March 2021",
    "is_open": true,
    "custom_fields":[{
        "id":"1",
        "type":"dropdown",
        "placeholder":"",
        "options":"hall12,hall11, halltamarind",
    },
    {
        "id":"1",
        "type":"textbox",
        "placeholder":"Enter Address",
        "options":""
    }],
    "shop_items": [{
        "id": 1,
        "item_name": "Paket Manis",
        "description": "Manis",
        "price": 3.5,
        "quantity": 100,
        "display_picture": "https://pintusingapura.org/static/image/paket01-2021.jpg",
    },{
        "id": 2,
        "item_name": "Paket Manis",
        "description": "Manis",
        "price": 3.5,
        "quantity": 100,
        "display_picture": "https://pintusingapura.org/static/image/paket01-2021.jpg",
    }]
}

