# Generated by Django 4.0.1 on 2022-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='quantity',
            new_name='original_quantity',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='original_quantity',
            field=models.IntegerField(db_column='quantity'),
        ),
    ]
