# Generated by Django 4.0.1 on 2022-03-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_quantity_shopitem_original_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='display_picture',
            field=models.TextField(),
        ),
    ]
