# Generated by Django 4.0.1 on 2022-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopitem_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='display_picture',
            field=models.TextField(),
        ),
    ]
