# Generated by Django 4.0.1 on 2022-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='custom_order_id',
            field=models.TextField(default=''),
        ),
    ]
