# Generated by Django 4.0.1 on 2022-03-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_display_picture'),
        ('cart', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartcustom',
            old_name='option',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='cartcustom',
            name='type',
        ),
        migrations.AddField(
            model_name='cartcustom',
            name='shop_custom_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.shopcustom'),
            preserve_default=False,
        ),
    ]
