# Generated by Django 4.0.1 on 2022-03-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_display_picture'),
        ('cart', '0003_rename_option_cartcustom_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcustom',
            name='shop_custom_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopcustom'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shop_item_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem'),
        ),
    ]
