# Generated by Django 4.0.1 on 2022-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('admin', 'admin'), ('not_registered', 'not_registered')], default='not_registered', max_length=15),
        ),
    ]
