# Generated by Django 4.0.1 on 2022-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='emergency_contact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='buyer',
            name='emergency_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_otp',
            field=models.CharField(default='secret_otp', max_length=255),
        ),
    ]
