# Generated by Django 4.0.1 on 2022-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_buyer_emergency_contact_buyer_emergency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voting_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='voting_verified',
            field=models.BooleanField(default=False),
        ),
    ]
