# Generated by Django 4.0.1 on 2022-02-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
    ]
