# Generated by Django 4.0.1 on 2022-03-23 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_rename_option_ordercustom_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercustom',
            name='type',
        ),
        migrations.AlterField(
            model_name='order',
            name='from_user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
